import { createHash, randomUUID } from 'node:crypto'
import webpush, { type PushSubscription as WebPushSubscription } from 'web-push'
import { readLocalJsonFresh, updateLocalJson } from './local-store'
import type { AppRole } from './auth'
import type { PaymentNotification } from './payment-notifications'

export type StoredPushSubscription = WebPushSubscription & { id:string; userId:string; role:AppRole; deviceId:string; createdAt:string; updatedAt:string; disabledAt?:string }
type PushStore={subscriptions:StoredPushSubscription[]}
export type PushDelivery={subscriptionId:string;deviceId:string;status:'pending'|'delivered'|'retrying'|'expired'|'failed';attempts:number;nextAttemptAt:string|null;lastStatus?:number;lastError?:string;deliveredAt?:string;terminalAt?:string}
export type PushOutboxItem={id:string;notificationId:string;eventId:string;recipientUserId:string;recipientRole:AppRole;subscriptionId:string;deviceId:string;payload:string;status:'pending'|'delivering'|'retrying'|'delivered'|'failed';attempts:number;nextAttemptAt:string|null;createdAt:string;updatedAt:string;deliveredAt?:string;terminalAt?:string;lastStatus?:number;lastError?:string;leaseId?:string;leaseExpiresAt?:string;deliveries:PushDelivery[]}
type NotificationStore={notifications:PaymentNotification[];pushOutbox?:PushOutboxItem[]}
const SUBSCRIPTIONS_FILE='payment-push-subscriptions.json',SUBSCRIPTIONS_EMPTY:PushStore={subscriptions:[]}
const NOTIFICATIONS_FILE='payment-notifications.json',NOTIFICATIONS_EMPTY:NotificationStore={notifications:[],pushOutbox:[]}
export const PUSH_RETRY_DELAYS_MS=[60_000,5*60_000,15*60_000,60*60_000,6*60*60_000,24*60*60_000] as const
export const PUSH_LEASE_MS=30_000
export type PushTransport=(subscription:WebPushSubscription,payload:string,options:{TTL:number;urgency:'high';topic:string})=>Promise<unknown>
const subscriptionId=(endpoint:string)=>`sub-${createHash('sha256').update(endpoint).digest('hex').slice(0,32)}`
const clean=(value:unknown)=>String(value instanceof Error?value.message:value).replace(/https?:\/\/\S+/g,'[endpoint]').replace(/[A-Za-z0-9_-]{40,}/g,'[redacted]').slice(0,300)

export function paymentPushConfiguration(){const publicKey=process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY?.trim().replace(/\s+/g,'')||'',privateKey=process.env.VAPID_PRIVATE_KEY?.trim().replace(/\\n/g,'').replace(/\s+/g,'')||'',subject=process.env.VAPID_SUBJECT?.trim()||'mailto:accounts@bsmindia.com';const base64=/^[A-Za-z0-9_-]+$/;return{configured:publicKey.length>=80&&privateKey.length>=40&&base64.test(publicKey)&&base64.test(privateKey)&&/^(mailto:|https:)/.test(subject),publicKey}}
export async function savePaymentPushSubscription(userId:string,role:AppRole,deviceId:string,subscription:WebPushSubscription){const now=new Date().toISOString(),id=subscriptionId(subscription.endpoint);await updateLocalJson(SUBSCRIPTIONS_FILE,SUBSCRIPTIONS_EMPTY,store=>{const old=store.subscriptions.find(item=>item.endpoint===subscription.endpoint);return{subscriptions:[{...subscription,id,userId,role,deviceId,createdAt:old?.createdAt||now,updatedAt:now},...store.subscriptions.filter(item=>item.endpoint!==subscription.endpoint&&!(item.userId===userId&&item.deviceId===deviceId))]}})}
export async function removePaymentPushSubscription(userId:string,endpoint:string){await updateLocalJson(SUBSCRIPTIONS_FILE,SUBSCRIPTIONS_EMPTY,store=>({subscriptions:store.subscriptions.filter(item=>!(item.userId===userId&&item.endpoint===endpoint))}))}
export async function hasPaymentPushSubscription(userId:string,endpoint:string,deviceId:string){const store=await readLocalJsonFresh(SUBSCRIPTIONS_FILE,SUBSCRIPTIONS_EMPTY);return store.subscriptions.some(item=>item.userId===userId&&item.endpoint===endpoint&&item.deviceId===deviceId&&!item.disabledAt)}
export async function activePaymentPushSubscriptions(){const store=await readLocalJsonFresh(SUBSCRIPTIONS_FILE,SUBSCRIPTIONS_EMPTY);return store.subscriptions.filter(item=>!item.disabledAt).map(item=>({...item,id:item.id||subscriptionId(item.endpoint)}))}
export function isPaymentPushEligible(notification:Pick<PaymentNotification,'recipientUserId'|'recipientRole'>,subscription:Pick<StoredPushSubscription,'userId'|'role'>){return subscription.userId===notification.recipientUserId&&subscription.role===notification.recipientRole}
export function createPushOutboxItem(notification:PaymentNotification,subscription:Pick<StoredPushSubscription,'id'|'endpoint'|'deviceId'>,now=new Date()):PushOutboxItem{const sid=subscription.id||subscriptionId(subscription.endpoint);return{id:`push-${notification.id}-${sid}`,notificationId:notification.id,eventId:notification.eventId,recipientUserId:notification.recipientUserId,recipientRole:notification.recipientRole,subscriptionId:sid,deviceId:subscription.deviceId,payload:JSON.stringify({title:notification.title,body:notification.body,url:notification.url,tag:notification.eventId,paymentId:notification.paymentId}),status:'pending',attempts:0,nextAttemptAt:now.toISOString(),createdAt:now.toISOString(),updatedAt:now.toISOString(),deliveries:[{subscriptionId:sid,deviceId:subscription.deviceId,status:'pending',attempts:0,nextAttemptAt:now.toISOString()}]}}
function statusCode(error:unknown){return Number((error as {statusCode?:number})?.statusCode)||undefined}
function defaultTransport(subscription:WebPushSubscription,payload:string,options:{TTL:number;urgency:'high';topic:string}){const config=paymentPushConfiguration();webpush.setVapidDetails(process.env.VAPID_SUBJECT?.trim()||'mailto:accounts@bsmindia.com',config.publicKey,process.env.VAPID_PRIVATE_KEY!.trim().replace(/\\n/g,'').replace(/\s+/g,''));return webpush.sendNotification(subscription,payload,options)}
const retryableStatus=(code?:number)=>!code||code===408||code===425||code===429||code>=500

export async function deliverPushOutboxItem(id:string,transport:PushTransport=defaultTransport,now=new Date()){
 const config=paymentPushConfiguration();if(!config.configured){console.error('Payment push configuration invalid',{outboxId:id});return null}
 const leaseId=randomUUID();let claimed:PushOutboxItem|undefined
 await updateLocalJson(NOTIFICATIONS_FILE,NOTIFICATIONS_EMPTY,store=>({...store,pushOutbox:(store.pushOutbox||[]).map(item=>{const expired=item.status==='delivering'&&(!item.leaseExpiresAt||Date.parse(item.leaseExpiresAt)<=now.getTime());if(item.id!==id||(!['pending','retrying'].includes(item.status)&&!expired)||(item.nextAttemptAt&&Date.parse(item.nextAttemptAt)>now.getTime()))return item;claimed={...item,status:'delivering',attempts:item.attempts+1,nextAttemptAt:null,updatedAt:now.toISOString(),leaseId,leaseExpiresAt:new Date(now.getTime()+PUSH_LEASE_MS).toISOString()};return claimed})}))
 if(!claimed)return null
 const subscription=(await activePaymentPushSubscriptions()).find(item=>item.id===claimed!.subscriptionId&&item.userId===claimed!.recipientUserId&&item.role===claimed!.recipientRole&&item.deviceId===claimed!.deviceId)
 let status:PushOutboxItem['status']='failed',lastStatus:number|undefined,lastError:string|undefined,deliveredAt:string|undefined,terminalAt:string|undefined,nextAttemptAt:string|null=null,deliveryStatus:PushDelivery['status']='failed'
 if(!subscription){terminalAt=new Date().toISOString();lastError='Subscription is inactive'}else try{await transport(subscription,claimed.payload,{TTL:86400,urgency:'high',topic:createHash('sha256').update(claimed.eventId).digest('base64url').slice(0,32)});status='delivered';deliveryStatus='delivered';deliveredAt=new Date().toISOString()}catch(error){lastStatus=statusCode(error);lastError=clean(error);if(lastStatus===404||lastStatus===410){deliveryStatus='expired';terminalAt=new Date().toISOString();await updateLocalJson(SUBSCRIPTIONS_FILE,SUBSCRIPTIONS_EMPTY,s=>({subscriptions:s.subscriptions.map(x=>(x.id||subscriptionId(x.endpoint))===claimed!.subscriptionId?{...x,id:x.id||subscriptionId(x.endpoint),disabledAt:terminalAt}:x)}))}else if(retryableStatus(lastStatus)&&claimed.attempts<=PUSH_RETRY_DELAYS_MS.length){status='retrying';deliveryStatus='retrying';const base=PUSH_RETRY_DELAYS_MS[claimed.attempts-1],jitter=Math.floor(base*.2*Math.random());nextAttemptAt=new Date(now.getTime()+base+jitter).toISOString()}else{terminalAt=new Date().toISOString()}console.error('Payment push delivery failed',{outboxId:id,status:lastStatus,attempt:claimed.attempts,error:lastError})}
 let result:PushOutboxItem|undefined
 await updateLocalJson(NOTIFICATIONS_FILE,NOTIFICATIONS_EMPTY,store=>({...store,pushOutbox:(store.pushOutbox||[]).map(item=>{if(item.id!==id||item.leaseId!==leaseId)return item;const delivery:PushDelivery={subscriptionId:item.subscriptionId,deviceId:item.deviceId,status:deliveryStatus,attempts:item.attempts,nextAttemptAt,lastStatus,lastError,deliveredAt,terminalAt};result={...item,status,nextAttemptAt,updatedAt:new Date().toISOString(),deliveredAt,terminalAt,lastStatus,lastError,leaseId:undefined,leaseExpiresAt:undefined,deliveries:[delivery]};return result})}))
 return result||null
}
export async function processDuePushOutbox(transport:PushTransport=defaultTransport,now=new Date(),limit=25){const store=await readLocalJsonFresh(NOTIFICATIONS_FILE,NOTIFICATIONS_EMPTY),due=(store.pushOutbox||[]).filter(item=>{const expired=item.status==='delivering'&&(!item.leaseExpiresAt||Date.parse(item.leaseExpiresAt)<=now.getTime());return expired||(['pending','retrying'].includes(item.status)&&(!item.nextAttemptAt||Date.parse(item.nextAttemptAt)<=now.getTime()))}).slice(0,limit),results:PushOutboxItem[]=[];for(const item of due){const result=await deliverPushOutboxItem(item.id,transport,now);if(result)results.push(result)}return results}
export async function sendPaymentPushNotifications(notifications:PaymentNotification[],transport?:PushTransport){const ids=new Set(notifications.map(n=>n.id)),store=await readLocalJsonFresh(NOTIFICATIONS_FILE,NOTIFICATIONS_EMPTY),jobs=(store.pushOutbox||[]).filter(x=>ids.has(x.notificationId)),results=[];for(const job of jobs){const result=await deliverPushOutboxItem(job.id,transport);if(result)results.push(result)}return{sent:results.filter(x=>x.status==='delivered').length,configured:paymentPushConfiguration().configured}}
export async function pushDeliveryAudit(){const [notifications,subscriptions]=await Promise.all([readLocalJsonFresh(NOTIFICATIONS_FILE,NOTIFICATIONS_EMPTY),activePaymentPushSubscriptions()]);return{subscriptions:subscriptions.length,outbox:(notifications.pushOutbox||[]).reduce<Record<string,number>>((counts,item)=>(counts[item.status]=(counts[item.status]||0)+1,counts),{}),latestFailures:(notifications.pushOutbox||[]).filter(x=>x.lastError).slice(0,10).map(x=>({id:x.id,status:x.status,code:x.lastStatus,error:x.lastError}))}}
