import crypto from 'node:crypto'
import { apiError, apiOk } from '@/lib/api'
import { validatePaymentOrder } from '@/lib/payment-order-search'
import { createPaymentNotifications } from '@/lib/payment-notifications'
import { createPublicPayment, isPaymentAddedBy, listPayments, paymentAttachments } from '@/lib/payments'
import { cleanCustomer, cleanRemarks, isPaymentMode, parsePaymentAmount } from '@/lib/payment-domain'
import { storeProofFiles, validateProofFiles, deletePaymentProofs } from '@/lib/local-payment-proofs'
import { checkRateLimit, issuePaymentDeleteCapability, publicApiHeaders, sameOrigin, verifyPaymentDeleteCapability, verifySubmissionToken } from '@/lib/public-payment-security'
export const runtime='nodejs';export const dynamic='force-dynamic';const value=(v:unknown)=>String(v||'').trim()
function capabilities(request:Request){try{const parsed=JSON.parse(request.headers.get('x-payment-capabilities')||'{}');return parsed&&typeof parsed==='object'?parsed as Record<string,string>:{} }catch{return{}}}
export async function GET(request:Request){if(!checkRateLimit(request,'public-payment-list',120).allowed)return publicApiHeaders(apiError('Too many requests',429));try{const caps=capabilities(request);const owned=(await listPayments()).filter(p=>verifyPaymentDeleteCapability(caps[p.id]||'',p.publicDeleteTokenHash)).map(p=>({id:p.id,date:p.paymentDate||p.createdAt,salesOrderNumber:p.salesOrderNumber,customerName:p.customerName,paymentMode:p.paymentMode||null,paymentAmount:p.paymentAmount,status:p.status,remarks:p.remarks||null,addedBy:p.addedBy||null,attachments:paymentAttachments(p).map((proof,index)=>({name:proof.name,contentType:proof.contentType,size:proof.size,url:`/api/public/payments/${encodeURIComponent(p.id)}/proof?index=${index}&cap=${encodeURIComponent(caps[p.id])}`})),hasScreenshot:paymentAttachments(p).length>0}));return publicApiHeaders(apiOk({payments:owned}))}catch(e){return publicApiHeaders(apiError(e instanceof Error?e.message:'Could not load payments',500))}}
export async function POST(request:Request){
 if(!sameOrigin(request))return publicApiHeaders(apiError('Invalid request origin',403));if(!checkRateLimit(request,'public-payment-submit',8).allowed)return publicApiHeaders(apiError('Too many submissions',429))
 const form=await request.formData().catch(()=>null);if(!form)return publicApiHeaders(apiError('Multipart form data is required',400));if(!verifySubmissionToken(value(form.get('submissionToken'))))return publicApiHeaders(apiError('Form expired. Reload and try again.',403))
 const key=value(request.headers.get('idempotency-key'));if(!/^[a-zA-Z0-9_-]{16,100}$/.test(key))return publicApiHeaders(apiError('Invalid submission key',400))
 const customer=cleanCustomer(form.get('customerName')),amount=parsePaymentAmount(form.get('paymentAmount')),mode=form.get('paymentMode'),remarks=cleanRemarks(form.get('remarks')),addedBy=form.get('addedBy');if(!customer||amount===null||!isPaymentMode(mode)||remarks===null||!isPaymentAddedBy(addedBy))return publicApiHeaders(apiError('Invalid payment details',400))
 const orderId=value(form.get('salesOrderId')),number=value(form.get('salesOrderNumber'));if(Boolean(orderId)!==Boolean(number))return publicApiHeaders(apiError('Select an authoritative sales order',400));const order=orderId?await validatePaymentOrder(orderId,number):null;if(orderId&&!order)return publicApiHeaders(apiError('Selected sales order is invalid',400))
 const files=form.getAll('proofs').filter((v):v is File=>v instanceof File);try{validateProofFiles(files)}catch(e){return publicApiHeaders(apiError(e instanceof Error?e.message:'Invalid proofs',400))}
 const capability=issuePaymentDeleteCapability();const result=await createPublicPayment({customerName:order?.customerName||customer,salesOrderId:order?.id,salesOrderNumber:order?.salesOrderNumber,orderTotal:order?.orderTotal,salesOrderDate:order?.orderDate,paymentAmount:amount,paymentMode:mode,addedBy,remarks:remarks||undefined,publicDeleteTokenHash:capability.hash},key)
 if(result.duplicate)return publicApiHeaders(apiOk({receipt:{id:result.payment.id,salesOrderNumber:result.payment.salesOrderNumber,paymentAmount:result.payment.paymentAmount,status:result.payment.status},duplicate:true}))
 try{const attachments=await storeProofFiles(result.payment.id,files);const {setPaymentAttachments}=await import('@/lib/payments');const saved=await setPaymentAttachments(result.payment.id,attachments);await createPaymentNotifications(saved!,'public-salesman').catch(()=>{});return publicApiHeaders(apiOk({receipt:{id:result.payment.id,salesOrderNumber:result.payment.salesOrderNumber,paymentAmount:result.payment.paymentAmount,status:result.payment.status},deleteToken:capability.token,duplicate:false}))}catch(e){await deletePaymentProofs(result.payment.id);return publicApiHeaders(apiError(e instanceof Error?e.message:'Could not save proofs',500))}
}
