'use client'
import { useEffect, useRef, useState } from 'react'
import { createPortal } from 'react-dom'
export type ViewerProof = { name: string; contentType?: string; url: string }
export function PaymentProofViewer({ proofs, initial = 0, onClose }: { proofs: ViewerProof[]; initial?: number; onClose: () => void }) {
  const [index, setIndex] = useState(initial), [failed, setFailed] = useState(false), [zoom, setZoom] = useState(1)
  const touch = useRef<number | null>(null), proof = proofs[index]
  const move = (delta: number) => { setFailed(false); setZoom(1); setIndex(value => (value + delta + proofs.length) % proofs.length) }
  useEffect(() => { const key = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose(); if (e.key === 'ArrowLeft' && proofs.length > 1) move(-1); if (e.key === 'ArrowRight' && proofs.length > 1) move(1); if ((e.key === '+' || e.key === '=') && proof?.contentType !== 'application/pdf') setZoom(z => Math.min(3, z + .25)); if (e.key === '-' && proof?.contentType !== 'application/pdf') setZoom(z => Math.max(1, z - .25)) }; document.addEventListener('keydown', key); document.body.style.overflow = 'hidden'; return () => { document.removeEventListener('keydown', key); document.body.style.overflow = '' } }, [proofs.length, onClose, proof?.contentType])
  if (!proof) return null
  const pdf = proof.contentType === 'application/pdf' || /\.pdf$/i.test(proof.name)
  return createPortal(<div className="proof-viewer-backdrop" role="dialog" aria-modal="true" aria-label="Payment proof viewer" onMouseDown={e => { if (e.target === e.currentTarget) onClose() }}><section className="proof-viewer" onTouchStart={e => { touch.current = e.touches[0].clientX }} onTouchEnd={e => { if (touch.current == null) return; const delta = e.changedTouches[0].clientX - touch.current; if (Math.abs(delta) > 45 && proofs.length > 1) move(delta > 0 ? -1 : 1); touch.current = null }}><header><div><strong>{proof.name}</strong><span>{pdf ? 'PDF' : 'Image'} · {index + 1} of {proofs.length}</span></div>{!pdf && <div className="proof-zoom" role="group" aria-label="Image zoom"><button type="button" onClick={() => setZoom(z => Math.max(1, z - .25))} disabled={zoom === 1} aria-label="Zoom out">−</button><output aria-live="polite">{Math.round(zoom * 100)}%</output><button type="button" onClick={() => setZoom(z => Math.min(3, z + .25))} disabled={zoom === 3} aria-label="Zoom in">+</button></div>}<button type="button" onClick={onClose} aria-label="Close proof viewer">×</button></header><div className={`proof-stage ${zoom > 1 ? 'zoomed' : ''}`}>{proofs.length > 1 && <button className="proof-arrow left" type="button" onClick={() => move(-1)} aria-label="Previous proof">‹</button>}{failed ? <div className="proof-error"><strong>Proof could not be loaded</strong><button type="button" onClick={() => setFailed(false)}>Retry</button></div> : pdf ? <iframe title={proof.name} src={`${proof.url}#view=FitH&zoom=page-width`} onError={() => setFailed(true)} /> : <img src={proof.url} alt={proof.name} style={{ transform: `scale(${zoom})` }} onDoubleClick={() => setZoom(z => z === 1 ? 2 : 1)} onError={() => setFailed(true)} />}{proofs.length > 1 && <button className="proof-arrow right" type="button" onClick={() => move(1)} aria-label="Next proof">›</button>}</div>{proofs.length > 1 && <footer>{proofs.map((item, itemIndex) => <button type="button" key={`${item.url}-${itemIndex}`} className={itemIndex === index ? 'active' : ''} onClick={() => { setIndex(itemIndex); setZoom(1); setFailed(false) }} aria-label={`View proof ${itemIndex + 1}`} />)}</footer>}</section></div>, document.body)
}
