import assert from 'node:assert/strict'
import {readFile,writeFile} from 'node:fs/promises'
const files=['data/payment-order-index.json','data/zoho-circuit.json'],backup=new Map<string,string>();for(const f of files)backup.set(f,await readFile(f,'utf8').catch(()=>''))
const env={ZOHO_CLIENT_ID:process.env.ZOHO_CLIENT_ID,ZOHO_CLIENT_SECRET:process.env.ZOHO_CLIENT_SECRET,ZOHO_REFRESH_TOKEN:process.env.ZOHO_REFRESH_TOKEN,ZOHO_ORGANIZATION_ID:process.env.ZOHO_ORGANIZATION_ID,ZOHO_ACCOUNTS_DOMAIN:process.env.ZOHO_ACCOUNTS_DOMAIN,ZOHO_API_DOMAIN:process.env.ZOHO_API_DOMAIN,APP_LOCAL_ONLY:process.env.APP_LOCAL_ONLY}
Object.assign(process.env,{APP_LOCAL_ONLY:'true',ZOHO_CLIENT_ID:'test',ZOHO_CLIENT_SECRET:'test',ZOHO_REFRESH_TOKEN:'test',ZOHO_ORGANIZATION_ID:'1',ZOHO_ACCOUNTS_DOMAIN:'https://accounts.test',ZOHO_API_DOMAIN:'https://api.test'})
try{
 await writeFile('data/zoho-circuit.json','{}');let listCalls=0
 const rows=Array.from({length:10},(_,i)=>({salesorder_id:String(100+i),salesorder_number:`SO-${100-i}`,customer_name:`Customer ${i}`,total:100+i,date:'2026-09-26',created_time:new Date(Date.UTC(2026,8,26,10-i)).toISOString(),last_modified_time:new Date(Date.UTC(2026,8,26,10-i)).toISOString(),status:i===3?'closed':'open',currency_code:'INR'}))
 const fetcher=async(input:RequestInfo|URL)=>{const url=String(input);if(url.includes('/oauth/v2/token'))return new Response(JSON.stringify({access_token:'token',expires_in:3600}),{status:200});listCalls++;const parsed=new URL(url);assert.equal(parsed.searchParams.get('per_page'),'10');assert.equal(parsed.searchParams.get('page'),'1');assert.equal(parsed.searchParams.get('sort_column'),'created_time');assert.equal(parsed.searchParams.get('sort_order'),'D');assert.equal(parsed.searchParams.get('filter_by'),'Status.All');assert.equal(parsed.searchParams.has('status'),false);return new Response(JSON.stringify({salesorders:rows,page_context:{page:1,has_more_page:true,sort_column:'created_time',sort_order:'D'}}),{status:200})}
 const {refreshLatestTenPaymentOrders}=await import('../src/lib/payment-order-search.ts');const result=await refreshLatestTenPaymentOrders(fetcher as typeof fetch)
 assert.equal(listCalls,1,'manual refresh makes exactly one Zoho list call');assert.equal(result.orders.length,10);assert.equal(result.callsThisRun,1);assert.equal(result.syncState,'live');assert.equal(result.orders[3].rawStatus,'closed','closed orders are included');assert.deepEqual(result.orders.map(x=>x.salesOrderNumber),rows.map(x=>x.salesorder_number),'provider newest-first order is returned immediately')
 console.log('latest-ten refresh contract passed: one call, per_page=10, page=1, created_time DESC, Status.All, closed included, immediate newest-first response')
}finally{for(const [f,v] of backup)v?await writeFile(f,v):null;for(const [k,v] of Object.entries(env))v===undefined?delete process.env[k]:process.env[k]=v}
