import { apiError, apiOk } from '@/lib/api'
import { getUserStore, requirePermission } from '@/lib/auth'
import { canEditStandaloneUnauthorised, claimPayment, createLinkedPayment, createUnlinkedPayment, deletePayment, deletePaymentWithTombstone, isPaymentAddedBy, listPayments, listPaymentsForUserFresh, reverseClaimedAllocation, setPaymentAttachments, updatePayment, updatePaymentStatus, updateStandaloneUnauthorisedPayment } from '@/lib/payments'
import { orderSummary } from '@/lib/payment-settlement'
import { cleanCustomer, cleanRemarks, isPaymentMode, parsePaymentAmount } from '@/lib/payment-domain'
import { searchPaymentOrders, validatePaymentOrder } from '@/lib/payment-order-search'
import { deletePaymentProofs, deleteProofAttachments, storeProofFiles, validateProofFiles } from '@/lib/local-payment-proofs'
import { createClaimNotification, createPaymentNotifications, createStatusNotification, removePaymentNotifications } from '@/lib/payment-notifications'
export const runtime='nodejs';export const dynamic='force-dynamic';const text=(v:unknown)=>String(v||'').trim()
async function selectedOrder(id:unknown,number:unknown){const so=text(number);if(!so)return null;if(text(id))return validatePaymentOrder(text(id),so);const found=(await searchPaymentOrders(so,50)).orders.filter(o=>o.salesOrderNumber===so);return found.length===1?found[0]:null}
export async function GET(){const a=await requirePermission('payments.view');if(!a.ok)return a.response;try{const payments=await listPaymentsForUserFresh(a.user);const response=apiOk({payments});response.headers.set('Cache-Control','no-store, max-age=0');return response}catch(e){return apiError(e instanceof Error?e.message:'Could not read payments',500)}}
export async function POST(request:Request){
 const initial=await requirePermission('payments.view');if(!initial.ok)return initial.response
 const form=await request.formData().catch(()=>null);if(!form)return apiError('Multipart form data is required',400);const b=Object.fromEntries(form.entries())
 const kind=text(b.paymentType)||((initial.user.role==='Accounts')?'unauthorised':'regular');if(!['unauthorised','regular'].includes(kind))return apiError('Invalid payment type',400)
 if(initial.user.role==='Accounts'&&kind!=='unauthorised')return apiError('Accounts can only add unauthorised payments',403)
 const unauthorised=kind==='unauthorised';const auth=await requirePermission(unauthorised?'payments.createUnauthorised':'payments.createLinked');if(!auth.ok)return auth.response
 const amount=parsePaymentAmount(b.paymentAmount),files=form.getAll('proofs').filter((v):v is File=>v instanceof File);try{validateProofFiles(files)}catch(e){return apiError(e instanceof Error?e.message:'Invalid proofs',400)}
 const suppliedKey=text(b.idempotencyKey);if(suppliedKey&&!/^[a-zA-Z0-9_-]{16,100}$/.test(suppliedKey))return apiError('A valid submission key is required',400);const key=suppliedKey||crypto.randomUUID()
 let payment
 if(unauthorised){
  const utr=text(b.utrReference),rawCustomer=text(b.customerName),customer=rawCustomer?cleanCustomer(rawCustomer):'Unidentified customer',remarks=cleanRemarks(b.remarks);if(!utr||utr.length>120||!customer||amount===null||remarks===null)return apiError('UTR / Reference Number and a valid amount are required',400)
  try{const created=await createUnlinkedPayment({customerName:customer,utrReference:utr,paymentAmount:amount,paymentMode:isPaymentMode(b.paymentMode)?b.paymentMode:'Other',remarks:remarks||undefined,status:'Unauthorised',createdBy:auth.user.id,addedBy:isPaymentAddedBy(auth.user.name)?auth.user.name:undefined},key);payment=created.payment;if(created.duplicate)return apiOk({payment,duplicate:true})}catch(e){return apiError(e instanceof Error?e.message:'Could not save payment',500)}
 }else{
  const customer=cleanCustomer(b.customerName),remarks=cleanRemarks(b.remarks);if(!customer||amount===null||remarks===null||!isPaymentMode(b.paymentMode))return apiError('Valid linked payment fields are required',400)
  const order=await selectedOrder(b.salesOrderId,b.salesOrderNumber);if(!order)return apiError('Select a valid authoritative sales order',400)

  let owner=auth.user;if(auth.user.role==='Admin'){const ownerId=text(b.ownerUserId),users=(await getUserStore()).users;const selected=users.find(u=>u.id===ownerId&&u.active&&u.role==='Salesperson');if(!selected)return apiError('Select an active Salesperson',400);owner=selected}
  // Never consume client-provided owner/name fields for Salesperson requests.
  // Admin alone may select an active salesperson to submit on their behalf.
  const ownerLabel=auth.user.role==='Salesperson'?(auth.user.username||auth.user.name):(owner.name||owner.username)

  try{const created=await createLinkedPayment({customerName:order.customerName,salesOrderId:order.id,salesOrderNumber:order.salesOrderNumber,orderTotal:order.orderTotal,salesOrderDate:order.orderDate,paymentAmount:amount,paymentMode:b.paymentMode,remarks:remarks||undefined,createdBy:auth.user.id,ownerUserId:owner.id,addedBy:ownerLabel,salespersonName:owner.name},key);payment=created.payment;if(created.duplicate)return apiOk({payment,duplicate:true})}catch(e){return apiError(e instanceof Error?e.message:'Could not save payment',400)}
 }
 let uploaded:import('@/lib/payments').PaymentAttachment[]=[]
 try{uploaded=files.length?await storeProofFiles(payment.id,files):[];const saved=await setPaymentAttachments(payment.id,uploaded);if(!saved)throw new Error('Could not finalize payment');await createPaymentNotifications(saved,auth.user.id).catch(()=>{});return apiOk({payment:saved})}catch(e){await Promise.all([deletePayment(payment.id),deleteProofAttachments(uploaded)]);return apiError(e instanceof Error?e.message:'Could not save proofs',400)}
}
export async function PATCH(request:Request){
 if(request.headers.get('content-type')?.includes('multipart/form-data')){const session=await requirePermission('payments.view');if(!session.ok)return session.response;const form=await request.formData().catch(()=>null);if(!form)return apiError('Multipart form data is required',400);const b=Object.fromEntries(form.entries()),id=text(b.id),amount=parsePaymentAmount(b.paymentAmount),remarks=cleanRemarks(b.remarks);if(!id||amount===null||remarks===null||!isPaymentMode(b.paymentMode))return apiError('Valid amount, mode and remarks are required',400);const current=(await listPayments()).find(p=>p.id===id);if(!current)return apiError('Payment not found',404);const unlinked=canEditStandaloneUnauthorised(current,session.user);if(!unlinked){const auth=await requirePermission('payments.edit');if(!auth.ok)return auth.response}const replace=text(b.replaceProofs)==='true',files=form.getAll('proofs').filter((v):v is File=>v instanceof File);let saved;try{if(replace){validateProofFiles(files);saved=await storeProofFiles(id,files)}let updated;if(unlinked){const utr=text(b.utrReference),rawCustomer=text(b.customerName),customer=rawCustomer?cleanCustomer(rawCustomer):'Unidentified customer';if(!utr||utr.length>120||!customer)return apiError('UTR / Reference Number and a valid customer are required',400);updated=await updateStandaloneUnauthorisedPayment(id,session.user,{customerName:customer,utrReference:utr,paymentAmount:amount,paymentMode:b.paymentMode,remarks:remarks||undefined,...(replace?{attachments:saved}: {})})}else{const order=await selectedOrder(current.salesOrderId,current.salesOrderNumber);if(!order)return apiError('The authoritative sales order is no longer available',400);updated=await updatePayment(id,session.user,{paymentAmount:amount,paymentMode:b.paymentMode,remarks:remarks||undefined,...(replace?{attachments:saved}: {})},order.orderTotal)}if(!updated)throw new Error('Could not edit payment');if(replace)await deleteProofAttachments(current.attachments||[]).catch(()=>{});return apiOk({payment:updated})}catch(e){if(saved)await deleteProofAttachments(saved);const message=e instanceof Error?e.message:'Could not edit payment';return apiError(message,message.includes('cannot edit')?403:400)}}
 const b=await request.json().catch(()=>({}));if(b.action==='claim'){const auth=await requirePermission('payments.claim');if(!auth.ok)return auth.response;const users=(await getUserStore()).users,claimantId=auth.user.role==='Admin'?text(b.ownerUserId):auth.user.id;const authoritativeUser=users.find(user=>user.id===claimantId&&user.active&&user.role==='Salesperson');if(!authoritativeUser)return apiError(auth.user.role==='Admin'?'Select an active Salesperson':'Your Salesperson account is no longer active',auth.user.role==='Admin'?400:403);const order=await selectedOrder(b.salesOrderId,b.salesOrderNumber);if(!order)return apiError('Select a valid authoritative sales order',400);const amount=b.claimAmount===undefined?undefined:parsePaymentAmount(b.claimAmount),key=text(b.idempotencyKey)||undefined;if(b.claimAmount!==undefined&&amount===null)return apiError('A valid claim amount is required',400);if(key&&!/^[a-zA-Z0-9_-]{16,100}$/.test(key))return apiError('A valid claim key is required',400);try{const p=await claimPayment(text(b.id),authoritativeUser.id,authoritativeUser.name||authoritativeUser.username,order,amount??undefined,key);if(!p)return apiError('Unauthorised payment not found',404);await createClaimNotification(p).catch(()=>{});return apiOk({payment:p})}catch(e){return apiError(e instanceof Error?e.message:'Could not claim payment',400)}}
 const auth=await requirePermission('payments.approve');if(!auth.ok)return auth.response;const status=text(b.status) as 'Pending'|'Payment Received'|'Void';if(!['Pending','Payment Received','Void'].includes(status))return apiError('Invalid status',400)
 try{const before=(await listPayments()).find(p=>p.id===text(b.id));const p=await updatePaymentStatus(text(b.id),status,auth.user.id,text(b.reason)||undefined);if(p&&before?.status!==status)await createStatusNotification(p,status,before?.status).catch(()=>{});return p?apiOk({payment:p}):apiError('Payment not found or transition not allowed',404)}catch(e){return apiError(e instanceof Error?e.message:'Could not update payment',400)}
}
export async function DELETE(request:Request){const session=await requirePermission('payments.view');if(!session.ok)return session.response;const body=await request.json().catch(()=>({})),id=text(body.id)||text(new URL(request.url).searchParams.get('id')),reason=cleanRemarks(body.reason);if(!id)return apiError('Payment id is required',400);if(reason===null)return apiError('Deletion reason must be 500 characters or fewer',400);try{const all=await listPayments(),before=all.find(p=>p.id===id);if(!before)return apiError('Payment not found',404);const standalone=canEditStandaloneUnauthorised(before,session.user);if(!standalone){const auth=await requirePermission('payments.delete');if(!auth.ok)return auth.response}if(before.parentPaymentId){const result=await reverseClaimedAllocation(id,session.user,reason||'Claimed allocation reversed');return apiOk({deleted:true,reversed:true,id,payment:result.payment,duplicate:!result.changed})}const payment=await deletePaymentWithTombstone(id,session.user,reason||'Deleted by user');if(!payment)return apiError('Payment not found',404);const referenced=new Set(all.filter(p=>p.id!==id).flatMap(p=>(p.attachments||[]).map(a=>a.key)));const unreferenced=(before.attachments||[]).filter(a=>!referenced.has(a.key));await Promise.all([deletePaymentProofs(id),deleteProofAttachments(unreferenced),removePaymentNotifications(id)]);return apiOk({deleted:true,id})}catch(e){const message=e instanceof Error?e.message:'Could not delete payment';return apiError(message,message.includes('allocation history')?409:message.includes('cannot delete')||message.includes('cannot reverse')?403:message==='Payment not found'?404:400)}}
